global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'gatekeeper'
    static_configs:
      - targets: ['gatekeeper:4224']
    metrics_path: '/metrics'

  - job_name: 'keymaster'
    static_configs:
      - targets: ['keymaster:4226']
    metrics_path: '/metrics'

  - job_name: 'drawbridge'
    static_configs:
      - targets: ['drawbridge:4230']
    metrics_path: '/metrics'

  - job_name: 'hyperswarm-mediator'
    static_configs:
      - targets: ['hyperswarm-mediator:4232']
    metrics_path: '/metrics'

  - job_name: 'btc-mainnet-mediator'
    static_configs:
      - targets: ['btc-mainnet-mediator:4234']
    metrics_path: '/metrics'

  - job_name: 'btc-signet-mediator'
    static_configs:
      - targets: ['btc-signet-mediator:4236']
    metrics_path: '/metrics'
