# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Build & Test Docker images

on:
  pull_request:

jobs:
  build_test_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Setup env for Testing
        working-directory: ./tests/cli-tests
        run: ./generate_test_env.sh

      - name: Run Node
        run: |
          ./start-node-ci cli
          docker compose ps
          sleep 30

      - name: Run cli-tests
        env:
          CLI_TEST_CLEANUP: redis
        run: npm run test:cli

      - name: Grab logs
        if: always()
        run: |
          docker compose logs --no-color keymaster cli gatekeeper redis > docker-compose-logs.txt
          cat docker-compose-logs.txt

      - name: Teardown Docker
        run: |
          ./stop-node

      - name: Upload docker logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: docker-compose-logs
          path: docker-compose-logs.txt

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: E2E Artifacts
          path: e2e-results.xml

